<?php
global $neopackage;
$neopackage['timestamp'] ='1238081571';
$neopackage['source'] ='http://neoblogs.org';
$neopackage['ads'] = '<div id="wp125adwrap_2c">
<div class="wp125ad odd"><a href="http://neoblogs.org/index.php?adclick=4" rel="nofollow"><img src="http://neoxenos.net/files/church-ad-new-180.gif" alt="What Is Church" /></a></div>
<div class="wp125ad even"><a href="http://neoblogs.org/index.php?adclick=5" rel="nofollow"><img src="http://neoxenos.net/files/revolution-add-180.gif" alt="Revolution" /></a></div>
<div class="wp125ad odd"><a href="http://neoblogs.org/index.php?adclick=6" rel="nofollow"><img src="http://neoxenos.net/files/blog-ad.gif" alt="Blog Power" /></a></div>
</div>
';
?>
