<?php
global $neopackage;
$neopackage['timestamp'] ='1238081571';
$neopackage['source'] ='http://neoblogs.org';
$neopackage['glossary']=array (
  20 => 
  array (
    'permalink' => 'http://neoxenos.info/terms/lookup/ads',
    'term' => 'ads',
    'def' => '',
  ),
  13 => 
  array (
    'permalink' => 'http://neoxenos.info/terms/lookup/happiness',
    'term' => 'happiness',
    'def' => '',
  ),
  14 => 
  array (
    'permalink' => 'http://neoxenos.info/terms/lookup/joy',
    'term' => 'joy',
    'def' => '',
  ),
  3 => 
  array (
    'permalink' => 'http://neoxenos.info/terms/lookup/love-ethics',
    'term' => 'love-ethics',
    'def' => '',
  ),
  15 => 
  array (
    'permalink' => 'http://neoxenos.info/terms/lookup/thanksgiving',
    'term' => 'thanksgiving',
    'def' => 'From <i>Eucharisteo</i>, meaning to be openly, visibly, demonstrably thankful.',
  ),
);
?>